src/saga/adaptors/globus_online/go_file.py

Per your (Andre's) suggestion.
Enjoy parsing the diff for real changes.
You can keep the branch alive after merge.

Convert to locking "with"/by context manager.

---

src/saga/adaptors/slurm/slurm_job.py
src/saga/adaptors/torque/torquejob.py

Specifically to support Comet, also tested on Stampede.

General improvements to SLURM adaptor

---

src/saga/task.py

this is a very simple implementation.  We may want to reconsider task bookkeeping in general...

add tc.get_task(id)

---

src/saga/utils/pty_shell_factory.py

Pass value set using the `SAGA_PTY_SSH_TIMEOUT` environment variable to the `ConnectTimeout` option of the SSH command when attempting to set up a connection to a remote node.
`SAGA_PTY_SSH_TIMEOUT` can be a floating point value but this is converted to an `int` prior to passing it to the SSH command.
This fix ensures that connect attempts don't hang for a long period when the remote node is not accessible.

Passing ssh_timeout param to ssh ConnectTimeout option

---

src/saga/utils/pty_shell.py

This shoud address radical-cybertools/radical.pilot/issues/730.

avoid exception on undefined variable

---

src/saga/session.py

fix session dicumentation as suggested by Jeremy

---

src/saga/adaptors/condor/condorjob.py

This should only be merged after confirmation of functionality from RP devel (which at the moment stumbles over non-relative VE location specs)

allow gsissh for condor job submission

---

src/saga/adaptors/shell/shell_file.py

A very minor one but I keep encountering this...

Fixed string formatting error in shell_file adaptor

---

src/saga/exceptions.py

add traceback property

---

src/saga/utils/pty_shell.py

Thanks Mark - this should take care of the implicitness...

make $HOME explicit as landing dir

---

src/saga/utils/pty_shell.py

Fixed typo in PTYShell to get read_from_remote to work.

---

src/saga/adaptors/shell/shell_job.py

make sure we have a job description on reconnected jobs

---

src/saga/filesystem/directory.py

This fixed #520
this was the wrong place to mock around with URL completion -- the adaptor layer needs to take care of this (and does)

fix rel path on open

---

src/saga/adaptors/condor/condorjob.py

Stop-gap solution until the new branches are ready for public consumption.

Backport of 427a674.

---

src/saga/adaptors/shell/shell_job.py

The crux was that `self.shell` was not set to `None` after closing it, leading to a double close.

avoid double close for shell job service

---

src/saga/adaptors/lsf/lsfjob.py

Thanks @marksantcroos for the suggestion!!!
Cheers

Fixing Issue #568

---

src/saga/utils/pty_shell_factory.py

The patch is toward https://github.com/radical-cybertools/radical.pilot/issues/1099 -- it does not solve the problem, but should result in a better error message.

raise error on missing tools

---

src/saga/adaptors/pbspro/pbsprojob.py

small parsing fix for pbsnodes

attempt to fix #590

---

src/saga/adaptors/torque/torquejob.py

This backports a small set of changes in the torque adaptor from the `feature/osg_optimization` branch, to simplify deployment on titan (and other torque backends) with RP split branches.
The changes are localized and backward compatible.

backport ft and bulk ops for torque from osg_optimization

---

examples/context/context_ssh.py
examples/files/go_file_copy.py
examples/files/go_remotedir_list.py
examples/files/http_file_copy.py
examples/files/sftp_file_copy.py
examples/files/sftp_remotedir_list.py
examples/jobs/condorjob.py
examples/jobs/loadlevelerjob.py
examples/jobs/localjob.py
examples/jobs/localjobcontainer.py
examples/jobs/lsfjob.py
examples/jobs/pbsgsisshjob.py
examples/jobs/pbsjob.py
examples/jobs/sgejob.py
examples/jobs/slurmjob.py
examples/master_worker/master.py
examples/master_worker/worker.py
examples/misc/inherit_context.py
examples/resource/amazon_ec2.py
examples/resource/ec2.py
examples/tutorial/saga_example_local.py
examples/tutorial/saga_example_remote.py
examples/tutorial/saga_example_remote_cluster_staging.py
examples/tutorial/saga_example_remote_staging.py

Small PR which does nothing but changing mod and shebang of example scripts.

get examples to execute "normally"

---

src/saga/adaptors/sge/sgejob.py

0.46 stack broke RP on SGE because of incorrectly implemented job name.

Properly support SGE job name.

---

docs/source/conf.py

see https://readthedocs.org/projects/saga-python/builds/5131031/

try to make RTD happy

---

src/saga/adaptors/slurm/slurm_job.py

I mean, you may think it's a long way down the road to the chemist, but that's just peanuts to space.
-- Douglas Adams, The Hitchhiker's Guide to the Galaxy
Slurm at least is not able to grasp the emptiness of space...  This fixes the RP ticket #1319

Space is big. Really big. You just won't believe how vastly, hugely, mind-bogglingly big it is.

---

src/saga/adaptors/cobalt/cobaltjob.py
src/saga/adaptors/cpi/job/service.py
src/saga/adaptors/loadl/loadljob.py
src/saga/adaptors/lsf/lsfjob.py
src/saga/adaptors/pbs/pbsjob.py
src/saga/adaptors/pbspro/pbsprojob.py
src/saga/adaptors/redis/redis_advert.py
src/saga/adaptors/sge/sgejob.py
src/saga/adaptors/slurm/slurm_job.py
src/saga/adaptors/torque/torquejob.py

This supports job termination during the RP termination sequence.

container_cancel needs to accept timeout parameter

---

src/saga/utils/pty_shell.py
src/saga/utils/pty_shell_factory.py

Discovered yet another way how prompts can be screwed up :P

more thorough handling of $PROMPT_COMMAND

---

src/saga/adaptors/slurm/slurm_job.py

Iannis confirmed this fix to work as expected, thus merging.

fix split on reservation

---

examples/jobs/localjobcontainer.py
src/saga/adaptors/slurm/slurm_job.py

CPU architecture on NERSC's Cori

---

src/saga/adaptors/torque/torquejob.py

catch up on titan change,  code cleanup

get titan back to work

---

src/saga/adaptors/slurm/slurm_job.py

Pushing version check

---

setup.py

This change  is due to an error we got from Conda Forge Circle CI.

Adding git error in setup.py

---

src/saga/adaptors/slurm/slurm_job.py

We missed this Andre. If this is released let's move forward and do a hotfix. Do you agree?

Correcting type that was missed

---

src/saga/adaptors/slurm/slurm_job.py

I do not know how it disappeared.

fixing SBATCH GPU requirement for Bridges.

---

src/saga/adaptors/lsfsummit/lsfjobsummit.py

Change SMT from 1 to 4

---

src/radical/saga/adaptors/torque/torquejob.py

fix cray detection (failed on titan)

ensure cray detection

---

src/radical/saga/adaptors/lsf/lsfjob.py

Apparently, we did not radicalize LSF

RADICALIZATION of LSF adaptor

---

src/radical/saga/adaptors/slurm/slurm_job.py

first, tiger does not want a gpu arch specifier, so we need separate cases for bridges and tiger.  Second,  gres resoures are specified *per node*, so we need ppn to account for that.
This will be a hotfix release.

need separate gres spec for tiger

---

docs/source/conf.py

Propagating radical-cybertools/radical.entk#390

Update on documentation, small changes in the navigation bar, global TOC 

---

src/radical/saga/adaptors/pbspro/pbsprojob.py

Verify logger instance before use

---

examples/tutorial/mandelbrot/saga_mandelbrot.py

there was error because of type float couldn’t be converted into int inside mandelbrot.py

type error fix

---

docs/source/tutorial/part5.rst

Use Pillow instead, as PIL is basically dead. Pillow is a maintained fork of PIL.

replace PIL with Pillow

---

src/radical/saga/adaptors/slurm/slurm_job.py

Reverts radical-cybertools/radical.saga#792

Revert "Fix bridges GPU gres flag"

---

src/radical/saga/adaptors/slurm/slurm_job.py

Bridges 2.
PS: Can we reopen the discussion about GPUs and how we define them?

Bridges2 support

---

src/radical/saga/adaptors/shell/shell_job.py

state update was missing on `cancel` - this patches fixes it.

state update fixes

---

src/radical/saga/adaptors/slurm/slurm_job.py
tests/adaptors/test_slurm.py

@marksantcroos: would you mind giving this a try?  Thanks!
This fixes #830

simpler workdir switch, cleanup

---

src/radical/saga/adaptors/slurm/slurm_job.py

interpret OOM error on slurm

---

src/radical/saga/adaptors/slurm/slurm_job.py

This PR is adding SDSC Expanse to Slurm adapter.

adding SDSC expanse to Slurm adaptor

---

src/radical/saga/adaptors/slurm/slurm_job.py

See https://github.com/radical-collaboration/hpc-workflows/issues/138

another attempt to fix traverse support

---

.readthedocs.yml
LICENSE.md

forgot to sync a file, sorry... :-/

sync with ru

---

src/radical/saga/adaptors/slurm/slurm_job.py

AND set `qos` instead of `partition/queue` for Perlmutter@NERSC explicitly

added possibility to set `partition[:qos]` as `queue`

---

src/radical/saga/adaptors/slurm/slurm_job.py

https://github.com/radical-cybertools/other_activities/issues/74

fixed request for GPUs on Amarel (SLURM)
