radical-cybertools/radical.saga

src/saga/adaptors/slurm/slurm_job.py
list of host names which are to be considered
by the resource manager as candidate targets
taking advantage of the --nodelist sbatch option from SLURM:
--nodelist=<node name list>
Request a specific list of node names. The list may be specified as
a comma-separated list of node names, or a range of node names (e.g.
mynode[1-5,7,...]). Duplicate node names in the list will be ignored.
The order of the node names in the list is not important; the node names
will be sorted by SLURM.
=> implement candidate_hosts for slurm adaptor

src/saga/adaptors/condor/condorjob.py, src/saga/adaptors/loadl/loadljob.py, src/saga/adaptors/lsf/lsfjob.py, src/saga/adaptors/pbs/pbsjob.py, src/saga/adaptors/pbspro/pbsprojob.py, src/saga/adaptors/sge/sgejob.py, src/saga/adaptors/shell/shell_job.py
Even if they don't use it directly, they should not stumble over it, which
currently breaks RP with many adaptors.
Maybe this needs to be extended with a warning or so if the adaptor has no
native support for this?
Andre, any reason not to merge this now and possibly create tickets to solve it properly?
=> Add PROCESSES_PER_HOST to all job adaptors.

src/saga/session.py
Recreation of PR #445 targetting devel branch rather than master:
When a session is created without the default=False property, it sets up contexts for all the SSH keys in a user's ~/.ssh directory. If many keys are present in that directory, this results in a number of registered security contexts. When attempting an SSH connection, these contexts are tried in order to see if a connection can be made. If many invalid keys are tried, the remote side may reject the login attempt due to too many incorrect authentication attempts being made.
When adding an explicit context using session.add_context(ctx), this is added to the end of the context list meaning that all other security contexts are tried first when attempting authentication and authentication will fail before reaching the …
=> Add contexts to session at start of context list

src/saga/adaptors/torque/torquejob.py
NCSA recently suggested us to move from cores to nodes. As BW uses a default ppn of 1, this lead to a RP slot count of 1 per node.
=> Recent NCSA suggestion introduced regression.

src/saga/adaptors/shell/shell_job.py, tests/unittests/api/job/test_job.py
Recreating pull request #478 toward devel branch.
Here is the old PR's message:
>>This commit sets the session for ShellJobService. As far as I looked at the code, there are two methods called _set_session and get_session in saga.adaptors.cpi.base.CPIBase class which I think should be used in init_instance methods of Service classes to set the session on the service object correctly. However, this is not called in different job implementations such as pbs, sge and probably others. Shall we add this to all the other ones as well?
=> Fix #477, set session for shell job service

src/saga/adaptors/context/ssh.py
Suggested fix to #494 to address the problems described with this issue in handling file paths for SSH context key/cert file path properties that contain environment variables.
=> Allow use of environment vars in ssh context key/cert file paths

src/saga/adaptors/context/ssh.py
Further update to PR #496, addressing issue #494, to resolve case where either the key or cert (pub) parameter are not specified.
=> Update to #496 to take account of empty key/cert parameter.

src/saga/adaptors/pbs/pbsjob.py, src/saga/adaptors/pbspro/pbsprojob.py, src/saga/adaptors/torque/torquejob.py
Modified the PBS, PBSPro and Torque adaptors to resolve issue #500 that was preventing state callbacks from being correctly made when the job state monitor thread detects a change in state.
=> Fix for #500. Modified job state monitor to correctly identify state changes.

src/saga/adaptors/slurm/slurm_job.py, src/saga/utils/pty_shell.py
This made local shells behave differently than remote ones.
=> remove a semantically incorrect chdir

src/saga/adaptors/context/ssh.py
Proposed fix to #509. This takes spaces into account but not sure whether there are other characters that may also cause similar issues. Perhaps someone can review and see if this looks reasonable.
=> Fix to ssh context to handle passwords containing spaces

src/saga/adaptors/shell/shell_wrapper.sh
We need to re-instiate the default HUP handler to make sure that the whole process group goes away.
=> fix regression in job cancellation

src/saga/adaptors/pbs/pbsjob.py, src/saga/adaptors/pbspro/pbsprojob.py
This one keeps catching me out! I've been testing some code with PBS 11 and 13 platforms and after the check for PBS12 fails in [pbsjob.py:617](https://github.com/radical-cybertools/saga-python/blob/cd1fbfd942adbff2172ceb250771d9525ecde585/src/saga/adaptors/pbs/pbsjob.py#L617), the alternative attempt to grep the output of `pbsnodes -a` (`grep -E "(np|pcpu)[[:blank:]]*=" '`) then also fails resulting in the job failing with `Error running pbsnodes`.
It seems that PBS 11 and 13 require the same check as used for PBS 12 so I've added these two versions into this code path. Have updated both `pbsjob.py` and `pbsprojob.py` to ensure that this doesn't catch out anyone still using the old pbs adaptor.
=> Added new PBS versions to pbsnodes CPU count check.

src/saga/job/job.py
Removed duplicate `get_name` function in the `Job` class in `src/saga/job/job.py`.
=> Removed duplicate get_name function in job class

src/saga/adaptors/shell/shell_job.py
Fixes #586 by checking the start of the target file path when placing the shell job adapter `wrapper.sh` script into `~/.saga/...`. If the target path starts with `$HOME/` or `${HOME}/` then this is removed because sftp accepts a relative path as being relative to the authenticating user's home directory.
=> Fix for issue #586, removing HOME env var from shell wrapper script file path

src/saga/adaptors/slurm/slurm_job.py
This gets the `split_module` branch (and thus `experiment/aimes`) running on stampede.
=> re-enable fallback methods for slurm job containers, jd.name support

.gitignore, src/saga/adaptors/context/myproxy.py, src/saga/adaptors/sge/sgejob.py
This is my little contribution about discussion in https://github.com/radical-cybertools/saga-python/issues/578.
I was thinking about setting up a hierarchy in configurations in order to get this "'baseworking dir" available once for all adaptors (and be able to potentially override for a specific one).
By the way I noticed an error in your doc : the configuration file used is not named .saga.conf, but .saga.cfg (and this file does not allow indents)
=> Relative to discussion about #578

src/saga/adaptors/slurm/slurm_job.py
This fixes a spurious error message reported in https://github.com/radical-cybertools/radical.pilot/issues/1209
=> remove spurious debug logs

src/saga/adaptors/slurm/slurm_job.py
Old:
```
if total_cpu_count and number_of_processes:
```
is always true (set before). 
```
int(total_cpu_count / number_of_processes)
```
gives `0` if `total_cpu_count` is not set manually (Slurm error).
----
New:
Only sets `--cpus-per-task` if `processes_per_host` is not set.
Having both, `--cpus-per-task` and `--ntasks-per-node` doesn't make much sense anyways.
Also `--cpus-per-task` is quite annoying since it requires setting it to the number of hyperthreads for a full node.
=> Fixed processes per host (#ranks/node) in SLURM-settings.

src/saga/task.py
I am not sure how that went undetected for so long, but here we are...
=> fix task container get_state reval

src/saga/base.py, src/saga/session.py
Matteo - I forgot to assign this one to you, too -- its the counterpart to radical-cybertools/radical.pilot/pull/1539 on the SAGA layer, which now accepts the uid to be specified on session creation, and only throws the dices for a new ID if none is given.
This needs to be merged before radical-cybertools/radical.pilot/pull/1539 - but in its self its backward compatible (the uid parameter is optional).  It is in sync with all other Session constructors in the RCT stack.
=> accept SID settings from upper layers (RP)

src/saga/adaptors/slurm/slurm_job.py
All other SLURM versions will be treated as before. We need to find a clear way to push cores per node here.
I missed that one. It will fail if the queue the user submits has different cores per node, from the first one. Already stumbled upon it.
This change makes it specific to Stampede2 version, which has the correct number of cores per node in the first value.
=> Adding Stampede specific version check only.

src/radical/saga/adaptors/cobalt/cobaltjob.py, src/radical/saga/adaptors/loadl/loadljob.py, src/radical/saga/adaptors/pbs/pbsjob.py, src/radical/saga/adaptors/pbspro/pbsprojob.py, src/radical/saga/adaptors/sge/sgejob.py, src/radical/saga/adaptors/slurm/slurm_job.py, src/radical/saga/adaptors/torque/torquejob.py
This fixes #742 
All walltime divisions were not converted to integers for the hours when batch scripts were created
=> Fixing adaptors to pass tests

src/radical/saga/__init__.py, src/radical/saga/adaptors/slurm/slurm_job.py
also ensure baclward compatibility for cgi module (`parse_qs` is not exported anymore, but needs to be pulled from `urllib`).  I'll open a ticket for a proper cleanup.
=> traverse support

src/radical/saga/adaptors/shell/shell_wrapper.sh
This PR re-enables a code path which was in use in the past.  That code ensures that the shell adaptors `sh_wrapper.sh` times out after 300 seconds of inactivity.   I have recently seen some shell wrappers lingering on compute node, this patch should solve this.
=> re-introduce shell wrapper timeout

src/radical/saga/adaptors/slurm/slurm_job.py
Bridges require to define the GPUs per node in the gres flag. So when we are requesting `p100` the gres should look like `--gres=gpu:p100:2` for any number of GPUS.
This is a hot fix since we are not supporting any other GPU type on Bridges.
=> Fix bridges GPU gres flag

src/radical/saga/configs/registry_default.json
Should some other adaptors be removed (comment out in config) from the loading as well?
p.s. Redis adaptor is not removed completely, just not loading (if there will be a request for it, then it can be turned on and some it parts should be updated according to the latest version of RU)
=> Remove redis-adaptor loading

src/radical/saga/adaptors/shell/shell_job.py, src/radical/saga/adaptors/shell/shell_wrapper.sh, src/radical/saga/utils/pty_shell.py, tests/unittests/api/job/test_service.py
This adds an infrequent keepalive-`ping` between service instance and shell_wrapper so that the shell timeout does not kick in as long as the connection is up.
=> fix sh timeout for long running sessions

src/radical/saga/adaptors/shell/shell_job.py
Inside `ShellJob` there are several methods (`get_stdout`, `get_stderr`, `get_log`) that have a call `self.js.shell.run_sync`, should it be put into `with self.js._shell_lock:` construction?
=> Fix for ShellJob[Service]

src/radical/saga/task.py
Thread objects deprecated `isAlive` from python version 3.7 in favor of `is_alive`:
```
(base) iparask@js-17-185:$ conda create -n test python=3.7 -y;conda activate test;python -c 'import threading as mt;t = mt.Thread();print(t.isAlive.__doc__);exit();';conda deactivate;conda remove --all -n test -y
Return whether the thread is alive.
This method is deprecated, use is_alive() instead.
(base) iparask@js-17-185:$ conda create -n test python=3.6 -y;conda activate test;python -c 'import threading as mt;t = mt.Thread();print(t.is_alive.__doc__);exit();';conda deactivate;conda remove --all -n test -y
Return whether the thread is alive.
This method returns True just before the run() method starts until just
after the run() method terminates. The module function enumerate()
returns a list of all …
```
=> fixing python deprecation

src/radical/saga/adaptors/lsf/lsfjob.py
This PR aims to introduce `"-alloc_flags ipisolate"` for lsf jobs on Lassen. One use case is that distributed pytorch requires sockets opened without authentication, which isn't abiding LC security policy. This flag is accommodating with the system, and for more details: https://lc.llnl.gov/confluence/pages/viewpage.action?pageId=650674651
=> ip-isolate flag for distributed pytorch on lassen

src/radical/saga/adaptors/slurm/slurm_job.py
This is to reflect slurm options for gpus, and addressing issue #813 according to https://portal.xsede.org/sdsc-comet#gpu.
=> comet takes --gres for gpu

src/radical/saga/adaptors/slurm/slurm_job.py
To respond to #835 , GRES option is excluded from the Longhorn slurm script,
```
if gpu_count: script += "#SBATCH --gpus=%s\n" % gpu_count
```
is eliminated when host is `longhorn`.
=> longhorn GRES exception

examples/context/context_ssh.py, src/radical/saga/adaptors/cobalt/cobaltjob.py, src/radical/saga/adaptors/context/myproxy.py, src/radical/saga/adaptors/loadl/loadljob.py, src/radical/saga/adaptors/sge/sgejob.py, src/radical/saga/adaptors/shell/shell_job.py, src/radical/saga/adaptors/shell/shell_wrapper.sh, src/radical/saga/configs/adaptors_cobaltjob.json, src/radical/saga/configs/adaptors_myproxy.json, src/radical/saga/configs/adaptors_sgejob.json, src/radical/saga/configs/adaptors_shell_job.json, src/radical/saga/utils/pty_shell.py
This PR removes remnants of `$HOME/.radical` throughout the code base and consistently uses `$RADICAL_BASE/.radical` instead.  Fixes #838
=> consistent use of radical_base

src/radical/saga/adaptors/shell/shell_wrapper.sh
trapping is too slow it seems, and we need to delay juuuuust a bit before sending `SIGKILL`.  POSIX has no sub-second sleep, so we (ab)use `/dev/urandom` for a little busy-time.
This supports radical-cybertools/radical.pilot/pull/2725
=> allow to trap `SIGTERM` before `SIGKILL` is sent

src/radical/saga/exceptions.py
The SAGA exception overwriting the `repr` and `str` methods makes it impossible to *programmatically* inspect the raised exception.  They are also against Python conventions, so this PR removes them - SAGA now (correctly) relies on the `Exception` base class to do the right thing...
=> SAGA.Exception should not overwrite representation

src/radical/saga/adaptors/slurm/slurm_job.py, tests/adaptors/test_slurm.py
Same approach as for LSF adaptor - check env variable `RADICAL_SMT` first
=> enhance SMT control in Slurm adaptor 

src/radical/saga/adaptors/shell/shell_wrapper.py
With `python -X dev`, I frequently see output like the following.
```
/home/rp/rp-venv/lib/python3.9/site-packages/radical/saga/adaptors/shell/shell_wrapper.py:11: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/rp/rp-venv/lib/python3.9/site-packages/radical/saga/adaptors/shell/shell_wrapper.sh' mode='r' encoding='UTF-8'>
_WRAPPER_SCRIPT = open (os.path.dirname(__file__) + '/shell_wrapper.sh').read ()
Enable tracemalloc to get traceback where the object was allocated.
See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
```
This patch should take care of it.
=> Let shell_wrapper.py close file more promptly.

docs/source/index.rst
Establish a docutils target for `radical.saga`. Allows the root package module to be linked from inside or outside of the project (via intersphinx through the `objects.inv` file).
=> Provide a target for Sphinx :py:mod: role.
